// Code generated by mockery v2.50.4. DO NOT EDIT.

package cluster

import (
	cluster "fardjad.com/dqlite-vip/cluster"
	mock "github.com/stretchr/testify/mock"
)

// ClusterNodeFactoryFunc is an autogenerated mock type for the ClusterNodeFactoryFunc type
type ClusterNodeFactoryFunc struct {
	mock.Mock
}

type ClusterNodeFactoryFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *ClusterNodeFactoryFunc) EXPECT() *ClusterNodeFactoryFunc_Expecter {
	return &ClusterNodeFactoryFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: dataDir, bindCluster, join
func (_m *ClusterNodeFactoryFunc) Execute(dataDir string, bindCluster string, join []string) (cluster.ClusterNode, error) {
	ret := _m.Called(dataDir, bindCluster, join)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 cluster.ClusterNode
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, []string) (cluster.ClusterNode, error)); ok {
		return rf(dataDir, bindCluster, join)
	}
	if rf, ok := ret.Get(0).(func(string, string, []string) cluster.ClusterNode); ok {
		r0 = rf(dataDir, bindCluster, join)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cluster.ClusterNode)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, []string) error); ok {
		r1 = rf(dataDir, bindCluster, join)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClusterNodeFactoryFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ClusterNodeFactoryFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - dataDir string
//   - bindCluster string
//   - join []string
func (_e *ClusterNodeFactoryFunc_Expecter) Execute(dataDir interface{}, bindCluster interface{}, join interface{}) *ClusterNodeFactoryFunc_Execute_Call {
	return &ClusterNodeFactoryFunc_Execute_Call{Call: _e.mock.On("Execute", dataDir, bindCluster, join)}
}

func (_c *ClusterNodeFactoryFunc_Execute_Call) Run(run func(dataDir string, bindCluster string, join []string)) *ClusterNodeFactoryFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *ClusterNodeFactoryFunc_Execute_Call) Return(_a0 cluster.ClusterNode, _a1 error) *ClusterNodeFactoryFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClusterNodeFactoryFunc_Execute_Call) RunAndReturn(run func(string, string, []string) (cluster.ClusterNode, error)) *ClusterNodeFactoryFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewClusterNodeFactoryFunc creates a new instance of ClusterNodeFactoryFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClusterNodeFactoryFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClusterNodeFactoryFunc {
	mock := &ClusterNodeFactoryFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
