# syntax=docker/dockerfile:1

FROM dqlite-vip-base:latest AS builder

RUN mkdir -p /build
WORKDIR /build

COPY ./hack/deps.sh ./hack/deps.sh
COPY ./hack/env.sh ./hack/env.sh
COPY ./hack/static-dqlite.sh ./hack/static-dqlite.sh
RUN ./hack/static-dqlite.sh

COPY ./go.mod ./go.sum ./
RUN go mod download

COPY . ./
RUN just build-static

FROM scratch

COPY --from=builder /build/bin/static/dqlite-vip /usr/local/bin/dqlite-vip
CMD ["/usr/local/bin/dqlite-vip"]