// Code generated by mockery v2.50.4. DO NOT EDIT.

package utils

import (
	time "time"

	mock "github.com/stretchr/testify/mock"

	utils "fardjad.com/dqlite-vip/utils"
)

// BetterTickerFactoryFunc is an autogenerated mock type for the BetterTickerFactoryFunc type
type BetterTickerFactoryFunc struct {
	mock.Mock
}

type BetterTickerFactoryFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *BetterTickerFactoryFunc) EXPECT() *BetterTickerFactoryFunc_Expecter {
	return &BetterTickerFactoryFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: d
func (_m *BetterTickerFactoryFunc) Execute(d time.Duration) utils.BetterTicker {
	ret := _m.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 utils.BetterTicker
	if rf, ok := ret.Get(0).(func(time.Duration) utils.BetterTicker); ok {
		r0 = rf(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(utils.BetterTicker)
		}
	}

	return r0
}

// BetterTickerFactoryFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type BetterTickerFactoryFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - d time.Duration
func (_e *BetterTickerFactoryFunc_Expecter) Execute(d interface{}) *BetterTickerFactoryFunc_Execute_Call {
	return &BetterTickerFactoryFunc_Execute_Call{Call: _e.mock.On("Execute", d)}
}

func (_c *BetterTickerFactoryFunc_Execute_Call) Run(run func(d time.Duration)) *BetterTickerFactoryFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *BetterTickerFactoryFunc_Execute_Call) Return(_a0 utils.BetterTicker) *BetterTickerFactoryFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BetterTickerFactoryFunc_Execute_Call) RunAndReturn(run func(time.Duration) utils.BetterTicker) *BetterTickerFactoryFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewBetterTickerFactoryFunc creates a new instance of BetterTickerFactoryFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBetterTickerFactoryFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *BetterTickerFactoryFunc {
	mock := &BetterTickerFactoryFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
