// Code generated by mockery v2.50.4. DO NOT EDIT.

package utils

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// BetterTicker is an autogenerated mock type for the BetterTicker type
type BetterTicker struct {
	mock.Mock
}

type BetterTicker_Expecter struct {
	mock *mock.Mock
}

func (_m *BetterTicker) EXPECT() *BetterTicker_Expecter {
	return &BetterTicker_Expecter{mock: &_m.Mock}
}

// C provides a mock function with no fields
func (_m *BetterTicker) C() <-chan time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for C")
	}

	var r0 <-chan time.Time
	if rf, ok := ret.Get(0).(func() <-chan time.Time); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan time.Time)
		}
	}

	return r0
}

// BetterTicker_C_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'C'
type BetterTicker_C_Call struct {
	*mock.Call
}

// C is a helper method to define mock.On call
func (_e *BetterTicker_Expecter) C() *BetterTicker_C_Call {
	return &BetterTicker_C_Call{Call: _e.mock.On("C")}
}

func (_c *BetterTicker_C_Call) Run(run func()) *BetterTicker_C_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BetterTicker_C_Call) Return(_a0 <-chan time.Time) *BetterTicker_C_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BetterTicker_C_Call) RunAndReturn(run func() <-chan time.Time) *BetterTicker_C_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *BetterTicker) Stop() {
	_m.Called()
}

// BetterTicker_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type BetterTicker_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *BetterTicker_Expecter) Stop() *BetterTicker_Stop_Call {
	return &BetterTicker_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *BetterTicker_Stop_Call) Run(run func()) *BetterTicker_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BetterTicker_Stop_Call) Return() *BetterTicker_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *BetterTicker_Stop_Call) RunAndReturn(run func()) *BetterTicker_Stop_Call {
	_c.Run(run)
	return _c
}

// NewBetterTicker creates a new instance of BetterTicker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBetterTicker(t interface {
	mock.TestingT
	Cleanup(func())
}) *BetterTicker {
	mock := &BetterTicker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
