// Code generated by mockery v2.50.4. DO NOT EDIT.

package api

import (
	http "net/http"

	api "fardjad.com/dqlite-vip/api"

	mock "github.com/stretchr/testify/mock"
)

// BackgroundServerFactoryFunc is an autogenerated mock type for the BackgroundServerFactoryFunc type
type BackgroundServerFactoryFunc struct {
	mock.Mock
}

type BackgroundServerFactoryFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *BackgroundServerFactoryFunc) EXPECT() *BackgroundServerFactoryFunc_Expecter {
	return &BackgroundServerFactoryFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: addr, handler
func (_m *BackgroundServerFactoryFunc) Execute(addr string, handler http.Handler) api.BackgroundServer {
	ret := _m.Called(addr, handler)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 api.BackgroundServer
	if rf, ok := ret.Get(0).(func(string, http.Handler) api.BackgroundServer); ok {
		r0 = rf(addr, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.BackgroundServer)
		}
	}

	return r0
}

// BackgroundServerFactoryFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type BackgroundServerFactoryFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - addr string
//   - handler http.Handler
func (_e *BackgroundServerFactoryFunc_Expecter) Execute(addr interface{}, handler interface{}) *BackgroundServerFactoryFunc_Execute_Call {
	return &BackgroundServerFactoryFunc_Execute_Call{Call: _e.mock.On("Execute", addr, handler)}
}

func (_c *BackgroundServerFactoryFunc_Execute_Call) Run(run func(addr string, handler http.Handler)) *BackgroundServerFactoryFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(http.Handler))
	})
	return _c
}

func (_c *BackgroundServerFactoryFunc_Execute_Call) Return(_a0 api.BackgroundServer) *BackgroundServerFactoryFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BackgroundServerFactoryFunc_Execute_Call) RunAndReturn(run func(string, http.Handler) api.BackgroundServer) *BackgroundServerFactoryFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewBackgroundServerFactoryFunc creates a new instance of BackgroundServerFactoryFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBackgroundServerFactoryFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *BackgroundServerFactoryFunc {
	mock := &BackgroundServerFactoryFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
